/* Generated by build-hosted.js — do not edit. Rebuilt on every deploy. */
const VERSION = "sthree-29c6633392";
const SHELL = ["./", "./index.html", "./collection.html", "./manifest.webmanifest",
  "./assets/icons/icon-192.png", "./assets/icons/icon-512.png"];

self.addEventListener("install", e => {
  self.skipWaiting();
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(SHELL)).catch(() => {}));
});

self.addEventListener("activate", e => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== VERSION) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;

  // Pages: always try the network, so a change to a price or a photograph is
  // seen immediately. The cache only answers when the network cannot.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const net = await fetch(req);
        const c = await caches.open(VERSION); c.put(req, net.clone());
        return net;
      } catch (_) {
        return (await caches.match(req)) || (await caches.match("./index.html")) ||
               new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } });
      }
    })());
    return;
  }

  // Photographs and icons: served from the cache, refreshed behind the scenes.
  // A changed picture arrives under a changed name, so this cannot go stale.
  if (/\.(?:jpg|jpeg|png|webp|ico|webmanifest)$/i.test(new URL(req.url).pathname)) {
    e.respondWith((async () => {
      const hit = await caches.match(req);
      const net = fetch(req).then(r => {
        if (r && r.ok) caches.open(VERSION).then(c => c.put(req, r.clone()));
        return r;
      }).catch(() => null);
      return hit || (await net) || new Response("", { status: 504 });
    })());
  }
});
